CREATE TABLE TEST_HM(
  id     INTEGER  ,
    area_code VARCHAR2(45) ,
    area_name VARCHAR2(200) ,
    holiday_date DATE ,
    HOLIDAY_DESC VARCHAR2(400) ,
    HOLIDAY_TYPE        VARCHAR2(45));
 DROP TABLE   TEST_HM; 

ALTER TABLE TEST_HM ADD  (STATE varchar2(100),  Country  varchar2(100), district varchar2(100));


INSERT INTO   TEST_HM(id,area_code,area_name,holiday_date,HOLIDAY_DESC,HOLIDAY_TYPE) values(1,'100','Chennai','01-05-2019','May 1st','National')

SELECT *FROM TEST_HM ORDER BY HOLIDAY_DATE 
delete from TEST_HM where holiday_date='04/05/2019'

SELECT * FROM TEST_HM WHERE 
 EXTRACT(YEAR FROM HOLIDAY_DATE) ='2019' AND
EXTRACT(MONTH FROM HOLIDAY_DATE)= '01'
ORDER BY HOLIDAY_DATE ASC;

SELECT *FROM TEST_HM WHERE TRUNC(HOLIDAY_DATE)='06/01/2019' OR TRUNC(HOLIDAY_DATE)='06/02/2019';

DELETE FROM TEST_HM WHERE AREA_CODE='101';
select *from TEST_HM where AREA_CODE='101';

Insert into TEST_HM (ID,AREA_CODE,AREA_NAME,HOLIDAY_DATE,HOLIDAY_DESC,HOLIDAY_TYPE) values (1,'100','All',to_timestamp('06/01/2019','MM/DD/YYYY'),'Saturday','Weekend');
INSERT INTO TEST_HM (ID,AREA_CODE,AREA_NAME,HOLIDAY_DATE,HOLIDAY_DESC,HOLIDAY_TYPE) VALUES (1,'100','All',TO_TIMESTAMP('06/02/2019','MM/DD/YYYY'),'Sunday','Weekend');

SELECT  HOLIDAY_DATE,COUNT(*)   FROM TEST_HM GROUP BY HOLIDAY_DATE    
SELECT *FROM TEST_HM ORDER BY HOLIDAY_DATE asc;

SELECT * FROM TEST_HM WHERE 
 EXTRACT(YEAR FROM HOLIDAY_DATE) ='2019' AND
EXTRACT(MONTH FROM HOLIDAY_DATE)= '01'
ORDER BY HOLIDAY_DATE ASC;
